Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.6
  DisabledByDefault: true
  Exclude:
    - "bin/**/*"
    - "**/templates/**/*"
    - "**/vendor/**/*"
    - "coverage/**/*"
    - "client/**/*"
    - "frontend/**/*"
    - "log/**/*"
    - "node_modules/**/*"
    - "public/**/*"
    - "storage/**/*"
    - "tmp/**/*"
    - "db/schema.rb"

# Prefer &&/|| over and/or.
Style/AndOr:
  EnforcedStyle: conditionals

# Do not use braces for hash literals when they are the last argument of a
# method call.
Style/BracesAroundHashParameters:
  Enabled: true
  EnforcedStyle: context_dependent

# Align `when` with `case`.
Layout/CaseIndentation:
  Enabled: true

# Align comments with method definitions.
Layout/CommentIndentation:
  Enabled: true

Layout/EmptyLineAfterMagicComment:
  Enabled: false

# In a regular class definition, no empty lines around the body.
Layout/EmptyLinesAroundClassBody:
  Enabled: true

# In a regular method definition, no empty lines around the body.
Layout/EmptyLinesAroundMethodBody:
  Enabled: true

# In a regular module definition, no empty lines around the body.
Layout/EmptyLinesAroundModuleBody:
  Enabled: true

Layout/FirstParameterIndentation:
  Enabled: true

# Use Ruby >= 1.9 syntax for hashes. Prefer { a: :b } over { :a => :b }.
# rake タスクの順序の hash は rocket を許可する
Style/HashSyntax:
  Enabled: true
  Exclude:
    - "**/*.rake"
    - "Rakefile"

# Method definitions after `private` or `protected` isolated calls need one
# extra level of indentation.
Layout/IndentationConsistency:
  Enabled: true
  EnforcedStyle: rails

# Two spaces, no tabs (for indentation).
Layout/IndentationWidth:
  Enabled: true

Layout/LeadingCommentSpace:
  Enabled: true

Layout/SpaceAfterColon:
  Enabled: true

Layout/SpaceAfterComma:
  Enabled: true

Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: true

Layout/SpaceAroundKeyword:
  Enabled: true

Layout/SpaceAroundOperators:
  Enabled: true

Layout/SpaceBeforeComma:
    Enabled: true

Layout/SpaceBeforeFirstArg:
    Enabled: true

Style/DefWithParentheses:
  Enabled: true

# Defining a method with parameters needs parentheses.
Style/MethodDefParentheses:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always
  Exclude:
    - 'app/views/**/*.builder'
    - 'app/views/**/*.ruby'
    - 'db/migrate/**/*.rb'
    - 'db/schema.rb'

# Use `foo {}` not `foo{}`.
Layout/SpaceBeforeBlockBraces:
  Enabled: true

# Use `foo { bar }` not `foo {bar}`.
Layout/SpaceInsideBlockBraces:
  Enabled: true

# Use `{ a: 1 }` not `{a:1}`.
Layout/SpaceInsideHashLiteralBraces:
  Enabled: true

Layout/SpaceInsideParens:
  Enabled: true

# Check quotes usage according to lint rule below.
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/StringMethods:
  Enabled: true

# Detect hard tabs, no hard tabs.
Layout/Tab:
  Enabled: true

# Blank lines should not have any spaces.
Layout/TrailingBlankLines:
  Enabled: true

# No trailing whitespace.
Layout/TrailingWhitespace:
  Enabled: true

# Use quotes for string literals when they are enough.
Style/UnneededPercentQ:
  Enabled: true

# Align `end` with the matching keyword or starting expression except for
# assignments, where it should be aligned with the LHS.
Layout/EndAlignment:
  Enabled: true
  EnforcedStyleAlignWith: variable

# Use my_method(my_arg) not my_method( my_arg ) or my_method my_arg.
Lint/RequireParentheses:
  Enabled: true

Style/RedundantReturn:
  Enabled: true
  AllowMultipleReturnValues: true

Style/Semicolon:
  Enabled: true
  AllowAsExpressionSeparator: true

Metrics/AbcSize:
  Max: 24
  Exclude:
    - "db/seeds.rb"

Metrics/CyclomaticComplexity:
  Enabled: true

Metrics/LineLength:
  Max: 150
  Exclude:
    - "db/migrate/*.rb"
    - "spec/**/*_spec.rb"
    - "config/initializers/devise.rb"
    - "config/initializers/simple_form_bootstrap.rb"

Metrics/MethodLength:
  Max: 20
  Exclude:
    - "db/migrate/*.rb"
    - "db/seeds.rb"

Metrics/PerceivedComplexity:
  Enabled: true

Style/AsciiComments:
  Enabled: false

Metrics/ClassLength:
  Enabled: true
  Max: 100
  CountComments: false

Layout/ClassStructure:
  Enabled: true

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/ExtraSpacing:
  Exclude:
    - "db/migrate/*.rb"

Layout/IndentArray:
  EnforcedStyle: consistent

Layout/IndentHash:
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: aligned

Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*_spec.rb"

Metrics/BlockLength:
  Exclude:
    - "Rakefile"
    - "**/*.rake"
    - "spec/**/*.rb"
    - "Gemfile"
    - "Guardfile"
    - "config/environments/*.rb"
    - "config/routes.rb"
    - "config/routes/**/*.rb"
    - "*.gemspec"
    - "config/initializers/devise.rb"
    - "config/initializers/simple_form_bootstrap.rb"
    - "db/seeds.rb"
    - "app/views/**/*.json.jbuilder"

Performance/Casecmp:
  Enabled: false

Style/GuardClause:
  Enabled: true

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/IfInsideElse:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/OrAssignment:
  Enabled: false

Style/RedundantSelf:
  Enabled: true

Style/RescueStandardError:
  EnforcedStyle: implicit

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/YodaCondition:
  EnforcedStyle: forbid_for_equality_operators_only

Layout/EmptyLineAfterGuardClause:
  Enabled: true

Lint/EmptyWhen:
  Enabled: false

Lint/InheritException:
  EnforcedStyle: standard_error

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/OrAssignment:
  Enabled: false

Style/PerlBackrefs:
  AutoCorrect: false

Style/SymbolArray:
  Enabled: false

Style/TernaryParentheses:
  EnforcedStyle: require_parentheses_when_complex

Style/WordArray:
  Enabled: false

Style/ZeroLengthPredicate:
  Enabled: false

Lint/UselessAssignment:
  Enabled: true